#pragma once

/*
    Gran Turismo 3: A-Spec (Europe)
    Build ID : SCES-50294    Boot ELF : SCES_502.94

    GENERATED by tools/gt3/port_target.py from SCUS-97102.h - do not edit by hand;
    change that header and rerun the tool (the command is in the README).
    What each address is, and the evidence for it, is documented there: this
    file carries only the values, each with the source build's for reference.

    Every value was ported by function matching and code reference, and checked:
    9924 of 10138 functions pair as equivalent code (identical but for relocated
    fields); every code address lies in an equivalent function whose calls and
    data references agree with the map; every instruction word was re-read here
    and checked to be the same instruction.

    Functions holding these addresses that are NOT identical to the source
    build's - a frame count or float constant retuned for this build; around
    every address the header names, the code is equivalent:
      function 001DDAD0 (source build): different immediate at +0x444 (24030078 vs 24030064)
      function 001E7500 (source build): different immediate at +0x1B4 (2403000C vs 2403000A)
      function 001ECFC8 (source build): +0x10 float 60 vs 50
      function 001F7AE0 (source build): different word at +0x9E0 (2C421771 vs 2C421389)
      function 0027C138 (source build): different immediate at +0xC0 (264282B0 vs 26429BF0)
*/
#define GAME_REGION_EU 1
#define REGION_NAME                  "EU"         /* US "US" */
#define BUILD_NAME                   "SCES-50294" /* US "SCUS-97102" */
#define ELF_NAME                     "SCES_502.94" /* US "SCUS_971.02" */
#define GAME_FRAME_HZ                50           /* US 60 */

/* ------------------------------------------------------------------ startup */
#define INVOKER_HOOK_SITE            0x00100094   /* US 0x00100094 */
#define INVOKER_DELAY_SLOT           0x00100098   /* US 0x00100098 */
#define INVOKER_RETURN_ADDR          0x0010009C   /* US 0x0010009C */

/* ------------------------------------------------------- memory / the pool */
#define POOL_BASE_GLOBAL             0x00354B70   /* US 0x003531D0 */
#define POOL_LIMIT_GLOBAL            0x00354B74   /* US 0x003531D4 */
#define POOL_GUARD_GLOBAL            0x00354B68   /* US 0x003531C8 */
#define POOL_INIT_FUNC               0x0026D460   /* US 0x0026C228 */
#define SBRK_BREAK_GLOBAL            0x00309094   /* US 0x00307A14 */
#define GAME_END                     0x004B461C   /* US 0x004B2C0C */
#define PLUGIN_BASE_ADDRESS          0x004B4680   /* US 0x004B2C80 */
#define PLUGIN_RESERVE_BYTES         0x10000      /* US 0x10000 */
#define POOL_BASE_VALUE              0x004B461C   /* US 0x004B2C0C */
#define POOL_BASE_NEW                0x004C4680   /* US 0x004C2C80 */

/* --------------------------------------------------------------- game libc */
#define ADDR_sprintf                 0x0026D950   /* US 0x0026C718 */
#define ADDR_printf                  0x0026D8C8   /* US 0x0026C690 */
#define ADDR_malloc                  0x0026D5E0   /* US 0x0026C3A8 */
#define ADDR_free                    0x0026D5B8   /* US 0x0026C380 */
#define ADDR_memset                  0x0027ED70   /* US 0x0027DB38 */
#define ADDR_strcmp                  0x0027FC78   /* US 0x0027EA40 */
#define ADDR_strcpy                  0x0027FDBC   /* US 0x0027EB84 */
#define ADDR_operator_new            0x0027D370   /* US 0x0027C138 */
#define ADDR_operator_del            0x0027D2F8   /* US 0x0027C0C0 */
#define ADDR_FlushCache              0x00287120   /* US 0x00285EE0 */
#define ADDR_sio_putchar             0x002884A8   /* US 0x00287268 */

/* ------------------------------------------------------- model / animation */
#define ADDR_Model_animate           0x00225A78   /* US 0x002249F8 */
#define ADDR_Model_reset             0x00225BC8   /* US 0x00224B48 */
#define ADDR_Model_rebind            0x00225950   /* US 0x002248D0 */
#define ADDR_AnimRecord_reset        0x0024A100   /* US 0x00248FF8 */
#define ADDR_Model_relocate          0x00225680   /* US 0x00224600 */
#define ADDR_CourseModelSet_animate  0x001AA668   /* US 0x001A9768 */

/* ---------------------------------------------------------- RaceCarModel */
#define ADDR_RaceCarModel_update     0x001ABFF8   /* US 0x001AB0F8 */
#define ADDR_RaceCarModel_update_tail 0x001AC094   /* US 0x001AB194 */
#define ADDR_RaceCarModel_update_epi 0x001AC09C   /* US 0x001AB19C */
#define ADDR_CarModel_tailCall       0x0021FEE8   /* US 0x0021EE68 */
#define RACECARMODEL_CARMODEL_OFF    0x04         /* US 0x04 */
#define RACECARMODEL_CAR_OFF         0x6AC        /* US 0x6AC */
#define ADDR_CarModel_setModel       0x0021FB10   /* US 0x0021EA90 */
#define CARMODEL_MODEL_OFF           0x24         /* US 0x24 */
#define RACECAR_SETMODEL_SITE        0x001AAF78   /* US 0x001AA078 */
#define RACECAR_SETMODEL_WORD        0x0C087EC4   /* US 0x0C087AA4 */

/* ------------------------------------------------- the model SWITCH query */
#define CARMODEL_CB_VTABLE           0x00342598   /* US 0x00340C28 */
#define CARMODEL_CB_VTABLE_WORDS     8            /* US 8 */
#define CARMODEL_CB_SWITCH_SLOT      5            /* US 5 */
#define ADDR_CarModel_getSwitch      0x0021FD10   /* US 0x0021EC90 */
#define ADDR_setBlend                0x00226C80   /* US 0x00225C00 */

/* ------------------------------------------------------------- the squat */
#define ADDR_SquatSeam               0x001EA318   /* US 0x001E93D8 */
#define SQUAT_SEAM_WORD              0x0C07A766   /* US 0x0C07A396 */
#define ADDR_SuspForce               0x001E9D98   /* US 0x001E8E58 */
#define CAR_PHYS_OFF                 0xF84        /* US 0xF84 */
#define SUSP_SPEC_SPRING_OFF         0x14         /* US 0x14 */
#define CAR_SIDEBRAKE_OFF            0x13B4       /* US 0x13B4 */
#define CAR_VEL_X_OFF                0x140C       /* US 0x140C */
#define CAR_VEL_Z_OFF                0x1410       /* US 0x1410 */
#define CAR_SLOT_OFF                 0x136C       /* US 0x136C */

/* ------------------------------------------------ the Pod's emotion triggers */
#define CAR_FINISHED_OFF             0x1464       /* US 0x1464 */
#define CAR_RANK_OFF                 0x1465       /* US 0x1465 */
#define CAR_MESSAGE_OFF              0x14A0       /* US 0x14A0 */
#define CAR_FLAGS_OFF                0x14B9       /* US 0x14B9 */
#define CAR_GAUGE_OFF                0x14B0       /* US 0x14B0 */
#define ADDR_BattleLevel             0x001F6BA0   /* US 0x001F5C58 */
#define CAR_RACE_OFF                 0x04         /* US 0x04 */
#define RACE_CAR0_OFF                0xC8         /* US 0xC8 */
#define RACE_CAR_STRIDE              0x16DC       /* US 0x16DC */
#define RACE_NCARS_OFF               0xE384       /* US 0xE384 */
#define RACE_REL_OFF                 0xBA34       /* US 0xBA34 */
#define CAR_CONTACT_OFF              0x14BC       /* US 0x14BC */
#define CAR_CONTACT_STRIDE           0x34         /* US 0x34 */
#define CAR_CONTACT_COUNT            4            /* US 4 */
#define CONTACT_SURFACE_OFF          0x31         /* US 0x31 */
#define OFFTRACK_CLASS_MASK          0x5Cu        /* US 0x5Cu */
#define ADDR_CrashNotify             0x001E0DF0   /* US 0x001DFEB8 */
#define CRASH_NOTIFY_JAL_WORD        0x0C07837C   /* US 0x0C077FAE */
#define CRASH_SITE_OBJECT            0x001A220C   /* US 0x001A130C */
#define CRASH_SITE_CAR_STRUCK        0x001FD748   /* US 0x001FC800 */
#define CRASH_SITE_CAR_STRIKER       0x001FD75C   /* US 0x001FC814 */
#define CRASH_SITE_WALL_CORNER       0x001FF1BC   /* US 0x001FE274 */
#define CRASH_SITE_WALL_EDGE         0x001FF594   /* US 0x001FE64C */

/* ------------------------------------------------- Pod, not hooked (yet) */
#define ADDR_hashName                0x00232210   /* US 0x00231190 */
#define ADDR_carSpecBuilder          0x001DB218   /* US 0x001DA308 */
#define ADDR_carSpecBuilder_seam     0x001DB2BC   /* US 0x001DA3AC */
#define ADDR_specToM10_seam          0x001DCF40   /* US 0x001DC030 */

/* --------------------------------------------------- sound effects (Pod) */
#define SE_NAME_TABLE                0x002EA9B0   /* US 0x002E9380 */
#define SE_NAME_COUNT                40           /* US 40 */
#define SE_REG_LUI                   0x0022D570   /* US 0x0022C4F0 */
#define SE_REG_LUI_WORD              0x3C02002F   /* US 0x3C02002F */
#define SE_REG_ADDIU                 0x0022D578   /* US 0x0022C4F8 */
#define SE_REG_ADDIU_WORD            0x2451A9B0   /* US 0x24519380 */
#define SE_GET_LUI                   0x0022D608   /* US 0x0022C588 */
#define SE_GET_LUI_WORD              0x3C03002F   /* US 0x3C03002F */
#define SE_GET_ADDIU                 0x0022D610   /* US 0x0022C590 */
#define SE_GET_ADDIU_WORD            0x2463A9B0   /* US 0x24639380 */
#define SE_COUNT_SLTI                0x0022D568   /* US 0x0022C4E8 */
#define SE_COUNT_SLTI_WORD           0x2A420028   /* US 0x2A420028 */
#define ADDR_SE_bankArray            0x004A0680   /* US 0x0049ECC0 */
#define SE_BANK3                     0x004A06E0   /* US 0x0049ED20 */
#define ADDR_SE_bankLoader           0x0022D1C0   /* US 0x0022C140 */
#define SE_BANK_CTOR_N               0x0022D89C   /* US 0x0022C81C */
#define SE_BANK_CTOR_N_WORD          0x24110002   /* US 0x24110002 */
#define SE_BANK_EH_N                 0x0022D91C   /* US 0x0022C89C */
#define SE_BANK_EH_N_WORD            0x24020002   /* US 0x24020002 */
#define SE_BANK_DTOR_END             0x0022D7B8   /* US 0x0022C738 */
#define SE_BANK_DTOR_END_WORD        0x24500060   /* US 0x24500060 */
#define SE_RN01_LOAD_JAL             0x0022D510   /* US 0x0022C490 */
#define SE_RN01_LOAD_JAL_WORD        0x0C08B470   /* US 0x0C08B050 */
#define SE_SPU_PTR                   0x00354524   /* US 0x00352B8C */
#define SE_HDR_PTR                   0x00354528   /* US 0x00352B90 */
#define SE_HDR_LEFT                  0x0035452C   /* US 0x00352B94 */
#define SE_INF_OBJ                   0x00354530   /* US 0x00352B98 */
#define SE_SPU_RACE_BASE             0x000AC000   /* US 0x000AC000 */
#define ADDR_file_resolve            0x00241BF8   /* US 0x00240AF0 */
#define SE_VOLUME                    0x002F49E0   /* US 0x002F33B0 */
#define ADDR_SE_playRace             0x001A8650   /* US 0x001A7750 */
#define ADDR_SE_playCar              0x001A7DD8   /* US 0x001A6ED8 */
#define SE_RACE_MUTE                 0x00353B80   /* US 0x003521E8 */
#define SE_RACE_LEVEL                0x00353B78   /* US 0x003521E0 */
#define SE_RACE_FADE                 0x00353B7C   /* US 0x003521E4 */
#define ADDR_SE_acquire              0x0022D630   /* US 0x0022C5B0 */
#define ADDR_SE_noteToPitch          0x002699E8   /* US 0x002687B0 */
#define ADDR_SE_keyOn                0x002697E0   /* US 0x002685A8 */
#define ADDR_SE_voiceSetVolume       0x00268EA8   /* US 0x00267C70 */
#define ADDR_SE_channelStop          0x0022CF20   /* US 0x0022BEA0 */
#define CARMODEL_SNDSTATE_OFF        0x6C8        /* US 0x6C8 */
#define ADDR_sinf                    0x0026B828   /* US 0x0026A5F0 */
#define ADDR_cosf                    0x0026B3D8   /* US 0x0026A1A0 */

/* ================================================= Lupo 2 drivetrain features */
#define CAR_PARAM_OFF                0x10         /* US 0x10 */
#define CAR_TRANS_OFF                0x208        /* US 0x208 */
#define TRANS_COUNT_OFF              0x02         /* US 0x02 */
#define TRANS_AXLE_OFF               0x03         /* US 0x03 */
#define TRANS_INERTIA_OFF            0x0C         /* US 0x0C */
#define TRANS_TYPE_OFF               0x12         /* US 0x12 */
#define TRANS_RPMREF_OFF             0x2C         /* US 0x2C */
#define TRANS_REDLINE_OFF            0x2E         /* US 0x2E */
#define TRANS_CVTRPM_OFF             0x30         /* US 0x30 */
#define TRANS_RATIO_OFF              0x3C         /* US 0x3C */
#define TRANS_SHAFTINERTIA_OFF       0xB4         /* US 0xB4 */
#define CAR_WHEELBASE_OFF            0x28         /* US 0x28 */
#define CAR_FRONTAXLE_OFF            0x284        /* US 0x284 */
#define CAR_DT_OFF                   0xEC0        /* US 0xEC0 */
#define CAR_IDLE_OFF                 0x1D6        /* US 0x1D6 */
#define CAR_AI_OFF                   0xEC8        /* US 0xEC8 */
#define CAR_DRIVEIN_OFF              0x1304       /* US 0x1304 */
#define PHYS_WHEEL0_OFF              0x60         /* US 0x60 */
#define PHYS_WHEEL_STRIDE            0xA4         /* US 0xA4 */
#define WHEEL_SPEED_OFF              0x20         /* US 0x20 */
#define WHEEL_TYRESEL_OFF            0x24         /* US 0x24 */
#define WHEEL_BRAKE_OFF              0x90         /* US 0x90 */
#define PHYS_WTQ0_OFF                0x2F0        /* US 0x2F0 */
#define PHYS_WTQ_STRIDE              0x24         /* US 0x24 */
#define WTQ_FORCE_OFF                0x08         /* US 0x08 */
#define WTQ_DRIVE_OFF                0x0C         /* US 0x0C */
#define PHYS_REVERSE_OFF             0x380        /* US 0x380 */
#define PHYS_SHAFTRPM_OFF            0x390        /* US 0x390 */
#define PHYS_AI_OFF                  0x3E9        /* US 0x3E9 */
#define PHYS_CLUTCH_OFF              0x418        /* US 0x418 */
#define PHYS_STEER_OFF               0x41C        /* US 0x41C */
#define PHYS_ACCEL_OFF               0x428        /* US 0x428 */
#define PHYS_BRAKE_OFF               0x42C        /* US 0x42C */
#define PHYS_SIDEBRAKE_OFF           0x430        /* US 0x430 */
#define PHYS_GEAR_OFF                0x436        /* US 0x436 */
#define PHYS_CSTATE_OFF              0x437        /* US 0x437 */
#define PHYS_ATTIMER_OFF             0x43A        /* US 0x43A */
#define PHYS_OMEGA_OFF               0x448        /* US 0x448 */
#define PHYS_AXLESPD_OFF             0x458        /* US 0x458 */
#define PHYS_TRANSMODE_OFF           0x461        /* US 0x461 */
#define PHYS_SPEED_OFF               0x488        /* US 0x488 */
#define PHYS_SPEEDZ_OFF              0x48C        /* US 0x48C */
#define PHYS_RPM_OFF                 0x490        /* US 0x490 */
#define PHYS_THROTTLE_OFF            0x4A4        /* US 0x4A4 */
#define PHYS_TQMAX_OFF               0x4B0        /* US 0x4B0 */
#define PHYS_TQFRIC_OFF              0x4B4        /* US 0x4B4 */
#define PHYS_LATACC_OFF              0x4C8        /* US 0x4C8 */
#define PHYS_HOLD_OFF                0x4DC        /* US 0x4DC */
#define PHYS_AUTODRIVE_OFF           0x534        /* US 0x534 */
#define PHYS_HOLDTIME_OFF            0x536        /* US 0x536 */
#define PHYS_ENGSND_OFF              0x4E4        /* US 0x4E4 */
#define PHYS_W0_BITS_OFF             0xBF         /* US 0xBF */
#define PHYS_W1_BITS_OFF             0x163        /* US 0x163 */

/* -- the data path -------------------------------------------------------- */
#define ADDR_applyGear               0x00233E98   /* US 0x00232E18 */
#define APPLYGEAR_SITE               0x00233744   /* US 0x002326C4 */
#define APPLYGEAR_WORD               0x0C08CFA6   /* US 0x0C08CB86 */
#define APPLYGEAR_DELAY              0x00233748   /* US 0x002326C8 */
#define APPLYGEAR_DELAY_WORD         0x0220282D   /* US 0x0220282D */
#define ADDR_CarDataBase_getBlock    0x002325C8   /* US 0x00231548 */
#define CAREQ_DB_OFF                 0x1D0        /* US 0x1D0 */
#define PARAMDB_TBL_GEAR             17           /* US 17 */
#define DATABLOCK_NUM_OFF            0x08         /* US 0x08 */
#define DATABLOCK_ELEMSIZE_OFF       0x0A         /* US 0x0A */
#define DATABLOCK_ROWS_OFF           0x10         /* US 0x10 */
#define GEAR_ROW_TYPE_OFF            0x30         /* US 0x30 */
#define SPEC_RATIO_OFF               0xB6         /* US 0xB6 */
#define SPEC_GEARCOUNT_OFF           0xC8         /* US 0xC8 */
#define SPEC_GEARBOX_TYPE_OFF        0xE1         /* US 0xE1 */
#define SPEC_DT_LAYOUT_OFF           0xB2         /* US 0xB2 */
#define SPEC_DT_SUBTYPE_OFF          0xB3         /* US 0xB3 */

/* -- the Transmission constructor, 0x001E1C98 (a0 spec, a1 T, a2 engine, a3) -- */
#define ADDR_TransCtor               0x001E2BC8   /* US 0x001E1C98 */
#define TRANS_CTOR_CALL_1            0x001DD270   /* US 0x001DC360 */
#define TRANS_CTOR_CALL_2            0x001E34B0   /* US 0x001E2580 */
#define TRANS_CTOR_CALL_3            0x001E3544   /* US 0x001E2614 */
#define TRANS_CTOR_CALL_WORD         0x0C078AF2   /* US 0x0C078726 */
#define TRANS_COUNT_SITE             0x001E2EE8   /* US 0x001E1FB8 */
#define TRANS_COUNT_WORD             0x926300C8   /* US 0x926300C8 */
#define TRANS_COUNT_NEXT             0x001E2EEC   /* US 0x001E1FBC */
#define TRANS_COUNT_NEXT_WORD        0xA2230002   /* US 0xA2230002 */
#define TRANS_T2C_SITE               0x001E3264   /* US 0x001E2334 */
#define TRANS_T2C_WORD               0x10400002   /* US 0x10400002 */
#define TRANS_T2C_NEXT               0x001E3268   /* US 0x001E2338 */
#define TRANS_T2C_NEXT_WORD          0x24C201F4   /* US 0x24C201F4 */
#define TRANS_T2C_STORE_WORD         0xA622002C   /* US 0xA622002C */

/* -- setup and top speed ---------------------------------------------------- */
#define ADDR_TopSpeed                0x001DC1D8   /* US 0x001DB2C8 */
#define TOPSPEED_SITE                0x001DC40C   /* US 0x001DB4FC */
#define TOPSPEED_WORD                0x0C077076   /* US 0x0C076CB2 */
#define PARAM_TOPSPEED_OFF           0xDF8        /* US 0xDF8 */
#define PARAM_ENGINE_OFF             0x138        /* US 0x138 */
#define PARAM_RATIO1_OFF             0x258        /* US 0x258 */
#define PARAM_DRAG0_OFF              0xE50        /* US 0xE50 */
#define PARAM_DRAG1_OFF              0xE60        /* US 0xE60 */
#define PARAM_DRAG2_OFF              0xE64        /* US 0xE64 */
#define PARAM_DRAG3_OFF              0xE68        /* US 0xE68 */
#define ADDR_PowerCurve              0x001E2418   /* US 0x001E14E8 */
#define ADDR_EngCurveTorque          0x001E1AF0   /* US 0x001E0BC0 */
#define ADDR_EngCurveNet             0x001E1B68   /* US 0x001E0C38 */
#define ADDR_Lookup                  0x001D9EC8   /* US 0x001D8FB8 */
#define TOPSPEED_DRAG_TABLE          0x002D42A0   /* US 0x002D2CE0 */
#define TOPSPEED_DRAG_K              0x002D42B0   /* US 0x002D2CF0 */

/* -- per step ----------------------------------------------------------------- */
#define INITGEAR_SITE                0x001E5DC0   /* US 0x001E4E80 */
#define INITGEAR_WORD                0x44800000   /* US 0x44800000 */
#define INITGEAR_DELAY_WORD          0x46006034   /* US 0x46006034 */
#define INITGEAR_RESUME              0x001E5DC8   /* US 0x001E4E88 */
#define DIFFSTEP_SITE                0x001E9524   /* US 0x001E85E4 */
#define DIFFSTEP_WORD                0x0C0799CE   /* US 0x0C0795FE */
#define ADDR_DiffStep                0x001E6738   /* US 0x001E57F8 */
#define DRIVESTEP_SITE               0x001E952C   /* US 0x001E85EC */
#define DRIVESTEP_WORD               0x0C079AB6   /* US 0x0C0796E6 */
#define STEP_DELAY_WORD              0x0200202D   /* US 0x0200202D */
#define ADDR_DriveStep               0x001E6AD8   /* US 0x001E5B98 */
#define SHIFT_SITE                   0x001E953C   /* US 0x001E85FC */
#define SHIFT_WORD                   0x0C07A110   /* US 0x0C079D40 */
#define SHIFT2_SITE                  0x001E9544   /* US 0x001E8604 */
#define SHIFT2_WORD                  0x0C07A1C8   /* US 0x0C079DF8 */
#define ADDR_RpmClutch               0x001E8440   /* US 0x001E7500 */
#define ADDR_ShiftHandler            0x001E8720   /* US 0x001E77E0 */
#define ADDR_GearRequest             0x001E65D0   /* US 0x001E5690 */
#define ADDR_SetGear                 0x001E5DB8   /* US 0x001E4E78 */
#define TORQUE_SITE                  0x001E6BE0   /* US 0x001E5CA0 */
#define TORQUE_WORD                  0x0C0789C8   /* US 0x0C0785FC */
#define TORQUE_DELAY_WORD            0x0240202D   /* US 0x0240202D */
#define FREEREV_SITE                 0x001E8494   /* US 0x001E7554 */
#define FREEREV_DELAY_WORD           0x46010502   /* US 0x46010502 */
#define ADDR_EngineTorque            0x001E2720   /* US 0x001E17F0 */
#define ADDR_EngineNet               0x001E2698   /* US 0x001E1768 */
#define GEARIDX1_SITE                0x001E6C94   /* US 0x001E5D54 */
#define GEARIDX1_NEXT_WORD           0x46001506   /* US 0x46001506 */
#define GEARIDX2_SITE                0x001E8544   /* US 0x001E7604 */
#define GEARIDX2_NEXT_WORD           0xC6010448   /* US 0xC6010448 */
#define GEARIDX_WORD                 0x92020436   /* US 0x92020436 */
#define INERTIA_SITE                 0x001E6F7C   /* US 0x001E603C */
#define INERTIA_W0                   0x92030436   /* US 0x92030436 */
#define INERTIA_W1                   0xC621000C   /* US 0xC621000C */
#define INERTIA_W2                   0x00031080   /* US 0x00031080 */
#define INERTIA_W3                   0x02821021   /* US 0x02821021 */
#define INERTIA_W4                   0xC4400000   /* US 0xC4400000 */
#define INERTIA_W5                   0x14600002   /* US 0x14600002 */
#define INERTIA_W6                   0x46000982   /* US 0x46000982 */
#define INERTIA_W7                   0x46003187   /* US 0x46003187 */
#define INERTIA_RESUME               0x001E6F9C   /* US 0x001E605C */
#define ENGSTATE_SITE                0x001E7E30   /* US 0x001E6EF0 */
#define ENGSTATE_WORD                0x0C079F22   /* US 0x0C079B52 */
#define ADDR_EngineState             0x001E7C88   /* US 0x001E6D48 */
#define RPMSHAFT1_SITE               0x001E7D9C   /* US 0x001E6E5C */
#define RPMSHAFT2_SITE               0x001E84C8   /* US 0x001E7588 */
#define RPMSHAFT_WORD                0x0C079EFA   /* US 0x0C079B2A */
#define ADDR_RpmFromShaft            0x001E7BE8   /* US 0x001E6CA8 */
#define ADDR_ShaftSpeed              0x001E7B68   /* US 0x001E6C28 */
#define ROLL_SITE                    0x001DE878   /* US 0x001DD968 */
#define ROLL_WORD                    0xC4410000   /* US 0xC4410000 */
#define ROLL_DELAY_WORD              0x46020002   /* US 0x46020002 */
#define ROLL_NEXT                    0x001DE880   /* US 0x001DD970 */
#define ROLL_NEXT_WORD               0x4601A042   /* US 0x4601A042 */
#define CLUTCH_SITE                  0x001E5BAC   /* US 0x001E4C6C */
#define CLUTCH_WORD                  0x0C079430   /* US 0x0C079060 */
#define ADDR_AutoClutch              0x001E50C0   /* US 0x001E4180 */
#define AICLUTCH_SITE_1              0x001E5D4C   /* US 0x001E4E0C */
#define AICLUTCH_SITE_2              0x001E5D74   /* US 0x001E4E34 */
#define AICLUTCH_SITE_3              0x001E5D90   /* US 0x001E4E50 */
#define AICLUTCH_WORD                0x0C079142   /* US 0x0C078D76 */
#define ADDR_AiClutch                0x001E4508   /* US 0x001E35D8 */
#define ADDR_AiDriveA                0x001F8848   /* US 0x001F7900 */
#define ADDR_AiDriveB                0x001F8A28   /* US 0x001F7AE0 */
#define ENGSND_SITE                  0x001EC1C4   /* US 0x001EB284 */
#define ENGSND_WORD                  0x0C0782E6   /* US 0x0C077F18 */
#define ADDR_EngineSound             0x001E0B98   /* US 0x001DFC60 */
#define WHINE_SITE                   0x00178A08   /* US 0x00177FC8 */
#define WHINE_WORD                   0x0C0782A4   /* US 0x0C077ED6 */
#define WHINE_DELAY_WORD             0x03C0202D   /* US 0x03C0202D */
#define ADDR_Whine                   0x001E0A90   /* US 0x001DFB58 */
#define ADDR_tanf                    0x0026B8F8   /* US 0x0026A6C0 */
#define ADDR_TireOf                  0x001DC8C8   /* US 0x001DB9B8 */
#define TIRE_GRIP_OFF                0x00         /* US 0x00 */
#define TIRE_CURVE_OFF               0x48         /* US 0x48 */

/* -- the Dualnote --------------------------------------------------------- */
#define DT_SUBTAB_SLOT5              0x0033DF64   /* US 0x0033C624 */
#define DT_SUBTAB_SLOT5_WORD         0x001E37D0   /* US 0x001E28A0 */
#define DT_FR_HANDLER                0x001E3664   /* US 0x001E2734 */
#define DT_CLASSIFY_SITE             0x001DD27C   /* US 0x001DC36C */
#define DT_CLASSIFY_WORD             0x0C07DB8E   /* US 0x0C07D7BC */
#define DT_CLASSIFY_DELAY_WORD       0x92A500B3   /* US 0x92A500B3 */
#define ADDR_DriveClass              0x001F6E38   /* US 0x001F5EF0 */
#define SETUP_SITE                   0x001DECA8   /* US 0x001DDD98 */
#define SETUP_WORD                   0x0C07B7D0   /* US 0x0C07B3F2 */
#define SETUP_DELAY_WORD             0x0260202D   /* US 0x0260202D */
#define ADDR_SetupTail               0x001EDF40   /* US 0x001ECFC8 */
#define HYB_MASS_SITE                0x001DDE5C   /* US 0x001DCF4C */
#define HYB_MASS_WORD                0x90830004   /* US 0x90830004 */
#define HYB_MASS_DELAY_WORD          0x90820003   /* US 0x90820003 */
#define CAR_MASS_TABLE               0x002D3E70   /* US 0x002D28B0 */
